//! # Geometry-Driven Fixture Layout & Planning Pipeline
//!
//! ## Business Domain Rationale & Architectural Intent
//! In commercial building construction, light fixtures are positioned relative to structural
//! bay grids, ceiling panel bounds, room enclosures, and circulation paths — never as floating
//! points generated by arbitrary world-space periodic modulo functions.
//!
//! This module implements pure geometry-driven fixture planning:
//! - **Assembly Layouts**: Candidates are generated from structural bay phase/dimensions and ceiling zone bounds.
//!   Candidates are rejected if their footprint breaches zone boundaries, overlaps service voids,
//!   collides with structural columns, or sits directly over entry thresholds.
//! - **Corridor Layouts**: Candidates are placed along spine-local longitudinal coordinates, pitched according to
//!   ceiling height and corridor width, and aligned with corridor orientation. Junctions and thresholds are excluded.
//! - **Fabric Cell Layouts**: Placed at room centers with offsets for doorways and alignment for through-paths.
//!
//! ## Design Patterns: Strategy & Flyweight Patterns
//! 1. **Strategy Pattern**: Separate layout generators ([`generate_assembly_fixture_layouts`],
//!    [`generate_corridor_fixture_layouts`], [`generate_fabric_cell_fixture_layouts`]) embody distinct placement
//!    strategies for different architectural families.
//! 2. **Flyweight Pattern**: Point queries ([`fixture_at`], [`corridor_fixture_at`]) evaluate whether a world-space
//!    coordinate `(wx, wz)` falls within a canonical [`FixtureLayout`]. If contained, they return a [`FixtureSample`]
//!    with the exact stable panel center coordinates and ID.

use crate::domain::entities::architecture::{AssemblyInstance, CeilingZone, CirculationSpine};
use crate::domain::entities::fixture::{FixtureKind, FixtureLayout, FixtureSample, FixtureState};

use super::BackroomsLevel;
use super::fixture_maintenance::{electrical_condition_for_district, fixture_maintenance_state};

/// Fixture owner identifier used during spatial column composition.
#[derive(Debug, Clone, Copy)]
pub(crate) enum FixtureOwner<'a> {
    FabricCell {
        cell_x: i64,
        cell_z: i64,
        ceiling_units: f32,
        age: f32,
    },
    Assembly {
        assembly: &'a AssemblyInstance,
        zone: &'a CeilingZone,
    },
}

/// Pure hash calculation for deterministic maintenance seeding.
pub(crate) fn fixture_hash(seed: u32, salt: u64, x: i64, z: i64) -> f32 {
    let mut h = (seed as u64)
        ^ salt.wrapping_mul(0x9E37_79B9_7F4A_7C15)
        ^ (x as u64).rotate_left(17)
        ^ (z as u64).rotate_left(37);
    h ^= h >> 30;
    h = h.wrapping_mul(0xBF58_476D_1CE4_E5B9);
    h ^= h >> 27;
    h = h.wrapping_mul(0x94D0_49BB_1331_11EB);
    h ^= h >> 31;
    (h >> 40) as f32 / (1u64 << 24) as f32
}

/// Deterministic 64-bit fixture ID for a corridor fixture.
pub(crate) fn fixture_id_for_corridor(spine_id: u32, along_idx: i64, seed: u32) -> u64 {
    let mut h = (spine_id as u64)
        ^ (seed as u64).rotate_left(13)
        ^ (along_idx as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15);
    h ^= h >> 33;
    h = h.wrapping_mul(0xFF51_AFD7_ED55_8CCD);
    h ^= h >> 33;
    h
}

/// Generates valid geometry-derived fixture layouts for an Assembly ceiling zone.
pub(crate) fn generate_assembly_fixture_layouts(
    seed: u32,
    assembly: &AssemblyInstance,
    zone: &CeilingZone,
) -> Vec<FixtureLayout> {
    let mut layouts = Vec::new();
    let (min_x, min_z, max_x, max_z) = zone.area.bounds();

    let (half_x, half_z, pitch_x, pitch_z, kind) = if zone.height_units < 3.8 {
        (0.45, 0.45, 3.6, 3.6, FixtureKind::FluorescentPanel)
    } else if zone.height_units < 4.8 {
        (0.45, 0.45, 4.0, 4.0, FixtureKind::FluorescentPanel)
    } else {
        (0.60, 0.30, 4.8, 4.8, FixtureKind::FluorescentStrip)
    };

    let st = &assembly.structure;
    let bay_x = st.bay_x.max(pitch_x);
    let bay_z = st.bay_z.max(pitch_z);
    let phase_x = st.phase.0;
    let phase_z = st.phase.1;

    let start_kx = ((min_x - phase_x) / bay_x).floor() as i64 - 1;
    let end_kx = ((max_x - phase_x) / bay_x).ceil() as i64 + 1;
    let start_kz = ((min_z - phase_z) / bay_z).floor() as i64 - 1;
    let end_kz = ((max_z - phase_z) / bay_z).ceil() as i64 + 1;

    let district = electrical_condition_for_district(seed, assembly.id as u64, 0.0);

    for kx in start_kx..=end_kx {
        for kz in start_kz..=end_kz {
            let cx = phase_x + (kx as f32 + 0.5) * bay_x;
            let cz = phase_z + (kz as f32 + 0.5) * bay_z;

            // 1. Verify full fixture footprint polygon containment within CeilingZone
            let p_min_x = cx - half_x;
            let p_max_x = cx + half_x;
            let p_min_z = cz - half_z;
            let p_max_z = cz + half_z;

            if !zone.area.contains(p_min_x, p_min_z)
                || !zone.area.contains(p_max_x, p_min_z)
                || !zone.area.contains(p_min_x, p_max_z)
                || !zone.area.contains(p_max_x, p_max_z)
            {
                continue;
            }

            // 2. Reject candidate if overlapping service voids
            let overlaps_void = assembly
                .service_voids
                .iter()
                .any(|sv| sv.area.contains(cx, cz));
            if overlaps_void {
                continue;
            }

            // 3. Reject candidate if near opening / doorway threshold centerline
            let near_opening = assembly.openings.iter().any(|op| {
                let dx = cx - op.center.x;
                let dz = cz - op.center.z;
                dx * dx + dz * dz < 0.64
            });
            if near_opening {
                continue;
            }

            // 4. Reject candidate if covered by a structural column
            if BackroomsLevel::on_column(&assembly.structure, cx, cz) {
                continue;
            }

            // Deterministic 64-bit fixture identifier
            let id = ((assembly.id as u64) << 32)
                ^ (((kx & 0xFFFF) as u64) << 16)
                ^ ((kz & 0xFFFF) as u64)
                ^ 0xA55E_0000_0000_0000;

            let hval = fixture_hash(seed, 0xA55E, kx, kz);
            let state = if assembly.corruption.abandoned {
                FixtureState::Dead
            } else {
                fixture_maintenance_state(district, kind, hval)
            };

            layouts.push(FixtureLayout {
                id,
                kind,
                state,
                center_x: cx,
                center_z: cz,
                half_x,
                half_z,
                ceiling_units: zone.height_units,
                red_room: assembly.corruption.red_room,
            });
        }
    }

    layouts
}

/// Generates valid geometry-derived fixture layouts along a CirculationSpine.
pub(crate) fn generate_corridor_fixture_layouts(
    seed: u32,
    spine: &CirculationSpine,
    ceiling_h: f32,
) -> Vec<FixtureLayout> {
    let mut layouts = Vec::new();

    for seg in spine.path.windows(2) {
        let (start, end) = (seg[0], seg[1]);
        let min_x = start.x.min(end.x);
        let max_x = start.x.max(end.x);
        let min_z = start.z.min(end.z);
        let max_z = start.z.max(end.z);

        let dx = end.x - start.x;
        let dz = end.z - start.z;
        let length = (dx * dx + dz * dz).sqrt();
        if length < 2.0 {
            continue;
        }

        let is_horizontal = dz.abs() < 0.5;
        let (half_x, half_z) = if is_horizontal {
            (0.6, 0.3)
        } else {
            (0.3, 0.6)
        };

        if is_horizontal {
            let start_k = (min_x / 4.0).floor() as i64;
            let end_k = (max_x / 4.0).ceil() as i64;
            for k in start_k..=end_k {
                let cx = k as f32 * 4.0 + 0.45;
                let cz = start.z;
                if cx >= min_x - 1e-4 && cx <= max_x + 1e-4 {
                    let segment_idx = (k.abs() / 4) as u64;
                    let district_id = ((spine.id as u64) << 32) ^ segment_idx;
                    let district = electrical_condition_for_district(seed, district_id, 0.0);

                    let id = fixture_id_for_corridor(spine.id, k, seed);
                    let hval = fixture_hash(seed, 0xC0DF, spine.id as i64, k);
                    let state =
                        fixture_maintenance_state(district, FixtureKind::FluorescentStrip, hval);

                    layouts.push(FixtureLayout {
                        id,
                        kind: FixtureKind::FluorescentStrip,
                        state,
                        center_x: cx,
                        center_z: cz,
                        half_x,
                        half_z,
                        ceiling_units: ceiling_h,
                        red_room: false,
                    });
                }
            }
        } else {
            let start_k = (min_z / 4.0).floor() as i64;
            let end_k = (max_z / 4.0).ceil() as i64;
            for k in start_k..=end_k {
                let cx = start.x;
                let cz = k as f32 * 4.0 + 0.45;
                if cz >= min_z - 1e-4 && cz <= max_z + 1e-4 {
                    let segment_idx = (k.abs() / 4) as u64;
                    let district_id = ((spine.id as u64) << 32) ^ segment_idx;
                    let district = electrical_condition_for_district(seed, district_id, 0.0);

                    let id = fixture_id_for_corridor(spine.id, k, seed);
                    let hval = fixture_hash(seed, 0xC0DF, spine.id as i64, k);
                    let state =
                        fixture_maintenance_state(district, FixtureKind::FluorescentStrip, hval);

                    layouts.push(FixtureLayout {
                        id,
                        kind: FixtureKind::FluorescentStrip,
                        state,
                        center_x: cx,
                        center_z: cz,
                        half_x,
                        half_z,
                        ceiling_units: ceiling_h,
                        red_room: false,
                    });
                }
            }
        }
    }

    layouts
}

/// Generates valid geometry-derived fixture layouts for a fabric cell.
pub(crate) fn generate_fabric_cell_fixture_layouts(
    seed: u32,
    cell_x: i64,
    cell_z: i64,
    ceiling_units: f32,
    age: f32,
) -> Vec<FixtureLayout> {
    let mut layouts = Vec::new();
    let cell_size = 7.2f32;
    let cx = (cell_x as f32 + 0.5) * cell_size;
    let cz = (cell_z as f32 + 0.5) * cell_size;

    let kind = if ceiling_units < 3.8 {
        FixtureKind::FluorescentPanel
    } else {
        FixtureKind::FluorescentStrip
    };

    let (half_x, half_z) = if matches!(kind, FixtureKind::FluorescentStrip) {
        (0.6, 0.3)
    } else {
        (0.45, 0.45)
    };

    let district_id = ((cell_x >> 2) as u64) ^ (((cell_z >> 2) as u64) << 32);
    let district = electrical_condition_for_district(seed, district_id, age);
    let hval = fixture_hash(seed, 0xF1A7, cell_x, cell_z);
    let state = fixture_maintenance_state(district, kind, hval);

    let id = ((cell_x as u64).wrapping_mul(0x9E37_79B9)
        ^ (cell_z as u64).rotate_left(19)
        ^ (seed as u64).rotate_left(37))
        & 0x7FFF_FFFF_FFFF_FFFF;

    layouts.push(FixtureLayout {
        id,
        kind,
        state,
        center_x: cx,
        center_z: cz,
        half_x,
        half_z,
        ceiling_units,
        red_room: false,
    });

    layouts
}

/// Queries whether a world point `(wx, wz)` falls inside an owner fixture layout.
pub(crate) fn fixture_at(
    seed: u32,
    owner: FixtureOwner<'_>,
    wx: f32,
    wz: f32,
) -> Option<FixtureSample> {
    match owner {
        FixtureOwner::FabricCell {
            cell_x,
            cell_z,
            ceiling_units,
            age,
        } => {
            let layouts =
                generate_fabric_cell_fixture_layouts(seed, cell_x, cell_z, ceiling_units, age);
            layouts
                .into_iter()
                .find(|l| l.contains_point(wx, wz))
                .map(|l| l.to_sample())
        }
        FixtureOwner::Assembly { assembly, zone } => {
            let layouts = generate_assembly_fixture_layouts(seed, assembly, zone);
            layouts
                .into_iter()
                .find(|l| l.contains_point(wx, wz))
                .map(|l| l.to_sample())
        }
    }
}

/// Queries whether a world point `(wx, wz)` falls inside a corridor fixture layout.
pub(crate) fn corridor_fixture_at(
    seed: u32,
    spine: &CirculationSpine,
    ceiling_h: f32,
    wx: f32,
    wz: f32,
) -> Option<FixtureSample> {
    let layouts = generate_corridor_fixture_layouts(seed, spine, ceiling_h);
    layouts
        .into_iter()
        .find(|l| l.contains_point(wx, wz))
        .map(|l| l.to_sample())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::entities::architecture::{
        AssemblyInstance, CorruptionProfile, HostSegment, Polygon2, SpaceProgram, StructuralSystem,
        StructuralSystemInstance,
    };
    use crate::domain::entities::position::Position;

    #[test]
    fn corridor_fixtures_have_stable_center_and_id_across_queries() {
        let spine = CirculationSpine {
            id: 10,
            spine_kind: SpaceProgram::OpenOffice,
            path: vec![Position::new(0.0, 0.0), Position::new(20.0, 0.0)],
            width: 3.0,
        };

        let layouts = generate_corridor_fixture_layouts(42, &spine, 3.2);
        assert!(
            !layouts.is_empty(),
            "corridor should generate fixture layouts"
        );

        let first = &layouts[0];
        // Query points near the panel center
        let sample1 = corridor_fixture_at(42, &spine, 3.2, first.center_x, first.center_z).unwrap();
        let sample2 =
            corridor_fixture_at(42, &spine, 3.2, first.center_x + 0.1, first.center_z + 0.1)
                .unwrap();

        assert_eq!(sample1.id, sample2.id);
        assert_eq!(sample1.center_x, first.center_x);
        assert_eq!(sample2.center_x, first.center_x);
        assert_eq!(sample1.center_z, first.center_z);
        assert_eq!(sample2.center_z, first.center_z);
    }
}
